[project]
name = "somalia-agrifood-exploration"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas>=3.0.0",
    "google-genai>=1.60.0",
    "openai>=2.15.0",
    "python-dotenv>=1.2.1",
]
